### ISSUE TITLE
Docstring context differs from Vanilla Python highlighting

### ISSUE THREAD

**Issue by detly** [petervaro/python#42] opened 2017-11-17 04:45 UTC
The built-in highlighting applied to triple-quoted docstrings under a function def gives `comment.block.documentation.python` as a context. This package gives `string.quoted.double.block.python.3`. Should docstrings be given an extra context (whether the same as the built in scheme or not)?

**Comment by petervaro** [comment] 2017-12-17 10:34
Well, that was a decision I made years ago, but thanks for asking.  So the thing is, in Python those are not comments -- those are strings, special ones, yeah, **doc**-strings, but they are *just* strings.  Now of course you can argue, that any form of documentation can be considered as a comment, or should require a special care/highlight and on a good day, I would very likely agree with you.

However, the problem is, it could have an enormous amount of variations there, depending on your conventions, which not necessarily has to be PEP-8.  It can be constructed with grouping-parenthesis and multi line single or double quoted strings, or the same thing with `+` concatenation, or the same thing without parenthesis but with `\` line-continuation, or with triple quotes, or with any combination of these, or as a matter of fact, it can contain even comments between the string chunks, which will not be part of the doc-string!

So as you could see by now, Python only says, that it will treat a regular comment block, or any kind of valid string literal before any other token in a function, class or module as a special one, and will assign it to the `__doc__` slot of these objects but you cannot mix them for example.  This however is as permissive as it possibly can be!

Therefore, I decided, that I'm not going to be very clever about this, as one cannot truly be here, and I would treat the string literals as literals, and the comments as comments, and I will not follow the previously broken attempts.

**Closed by petervaro** 2017-12-17 10:34 UTC
